runserver:
	python manage.py runserver
check:
	python manage.py check
makemigrations:
	python manage.py makemigrations
migrate:
	python manage.py migrate
startapp:
	python manage.py startapp
createsuperuser:
	python manage.py createsuperuser
test:
	python manage.py test